version: '3'
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
    volumes:
      - .docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf